### ISSUE TITLE
Demo

### ISSUE THREAD

**Issue by ghost** [enesemini/edutalk#1]
Is dahr ein demo vorhanden?

**Comment by enesemini** [comment]
Hey @comtronix,

das Projekt habe ich als Matura-Arbeit bei einem Informatik-Lehrer an meiner Schule gemacht. Wir haben GitHub nur als Austausch-Plattform genutzt. 

Das Projekt wird nicht weitergeführt und ist nicht komplett abgeschlossen.

Es war auch eines meiner ersten Projekte, und daher auch nicht das beste, was die Struktur angeht. 

Hier kannst du aber einige Screenshots vom Projekt sehen:
[Edutalk Screenshots.zip](https://github.com/enesemini/edutalk/files/72788/Edutalk.Screenshots.zip)

Gruss Enes Emini
